define(function(){
	"use strict";

	var country = {
		isEuropean: function (countryCode2){
    	return europeanCountries.indexOf(countryCode2) !== -1;
    },

    isEU: function(countryCode2){
    	return EUCountries.indexOf(countryCode2) !== -1;
    },

    /**
      Compares two countries to see if they have the same name

      @param x two, three country code or english country name.
      @param y two, three country code or english country name.
      @returns true if they are the same.
    */
    compare: function(x, y){
      var a, b;
      for(var i=0; i<world.length; i++){
        a = a || check(world[i], x);
        b = b || check(world[i], y);

        if(a && b) break;
      }
      if(a && b && (a.code2 == b.code2)){
        return true;
      }
    }
	};

  function check(country, code){
    if(country.code2 == code || country.code3 == code || country.name.toLowerCase() == code.toLowerCase()){
      return true;
    }
    return false;
  }

  var world = [ { name: 'Afghanistan', code2: 'AF', code3: 'AFG', tld: [ '.af' ] },
  { name: 'Åland Islands',
    code2: 'AX',
    code3: 'ALA',
    tld: [ '.ax' ] },
  { name: 'Albania', code2: 'AL', code3: 'ALB', tld: [ '.al' ] },
  { name: 'Algeria', code2: 'DZ', code3: 'DZA', tld: [ '.dz' ] },
  { name: 'American Samoa',
    code2: 'AS',
    code3: 'ASM',
    tld: [ '.as' ] },
  { name: 'Andorra', code2: 'AD', code3: 'AND', tld: [ '.ad' ] },
  { name: 'Angola', code2: 'AO', code3: 'AGO', tld: [ '.ao' ] },
  { name: 'Anguilla', code2: 'AI', code3: 'AIA', tld: [ '.ai' ] },
  { name: 'Antarctica', code2: 'AQ', code3: 'ATA', tld: [ '.aq' ] },
  { name: 'Antigua and Barbuda',
    code2: 'AG',
    code3: 'ATG',
    tld: [ '.ag' ] },
  { name: 'Argentina', code2: 'AR', code3: 'ARG', tld: [ '.ar' ] },
  { name: 'Armenia', code2: 'AM', code3: 'ARM', tld: [ '.am' ] },
  { name: 'Aruba', code2: 'AW', code3: 'ABW', tld: [ '.aw' ] },
  { name: 'Ascension Island',
    code2: 'SH',
    code3: 'SHN',
    tld: [ '.ac' ] },
  { name: 'Australia', code2: 'AU', code3: 'AUS', tld: [ '.au' ] },
  { name: 'Austria', code2: 'AT', code3: 'AUT', tld: [ '.at' ] },
  { name: 'Azerbaijan', code2: 'AZ', code3: 'AZE', tld: [ '.az' ] },
  { name: 'Bahamas', code2: 'BS', code3: 'BHS', tld: [ '.bs' ] },
  { name: 'Bahrain', code2: 'BH', code3: 'BHR', tld: [ '.bh' ] },
  { name: 'Bangladesh', code2: 'BD', code3: 'BGD', tld: [ '.bd' ] },
  { name: 'Barbados', code2: 'BB', code3: 'BRB', tld: [ '.bb' ] },
  { name: 'Belarus', code2: 'BY', code3: 'BLR', tld: [ '.by' ] },
  { name: 'Belgium', code2: 'BE', code3: 'BEL', tld: [ '.be' ] },
  { name: 'Belize', code2: 'BZ', code3: 'BLZ', tld: [ '.bz' ] },
  { name: 'Benin', code2: 'BJ', code3: 'BEN', tld: [ '.bj' ] },
  { name: 'Bermuda', code2: 'BM', code3: 'BMU', tld: [ '.bm' ] },
  { name: 'Bhutan', code2: 'BT', code3: 'BTN', tld: [ '.bt' ] },
  { name: 'Bolivia', code2: 'BO', code3: 'BOL', tld: [ '.bo' ] },
  { name: 'Bonaire',
    code2: 'BQ',
    code3: 'BES',
    tld: [ '.an', '.nl' ] },
  { name: 'Bosnia and Herzegovina',
    code2: 'BA',
    code3: 'BIH',
    tld: [ '.ba' ] },
  { name: 'Botswana', code2: 'BW', code3: 'BWA', tld: [ '.bw' ] },
  { name: 'Bouvet Island',
    code2: 'BV',
    code3: 'BVT',
    tld: [ '.bv' ] },
  { name: 'Brazil', code2: 'BR', code3: 'BRA', tld: [ '.br' ] },
  { name: 'British Indian Ocean Territory',
    code2: 'IO',
    code3: 'IOT',
    tld: [ '.io' ] },
  { name: 'British Virgin Islands',
    code2: 'VG',
    code3: 'VGB',
    tld: [ '.vg' ] },
  { name: 'Brunei', code2: 'BN', code3: 'BRN', tld: [ '.bn' ] },
  { name: 'Bulgaria', code2: 'BG', code3: 'BGR', tld: [ '.bg' ] },
  { name: 'Burkina Faso',
    code2: 'BF',
    code3: 'BFA',
    tld: [ '.bf' ] },
  { name: 'Burundi', code2: 'BI', code3: 'BDI', tld: [ '.bi' ] },
  { name: 'Cambodia', code2: 'KH', code3: 'KHM', tld: [ '.kh' ] },
  { name: 'Cameroon', code2: 'CM', code3: 'CMR', tld: [ '.cm' ] },
  { name: 'Canada', code2: 'CA', code3: 'CAN', tld: [ '.ca' ] },
  { name: 'Cape Verde', code2: 'CV', code3: 'CPV', tld: [ '.cv' ] },
  { name: 'Cayman Islands',
    code2: 'KY',
    code3: 'CYM',
    tld: [ '.ky' ] },
  { name: 'Central African Republic',
    code2: 'CF',
    code3: 'CAF',
    tld: [ '.cf' ] },
  { name: 'Chad', code2: 'TD', code3: 'TCD', tld: [ '.td' ] },
  { name: 'Chile', code2: 'CL', code3: 'CHL', tld: [ '.cl' ] },
  { name: 'China', code2: 'CN', code3: 'CHN', tld: [ '.cn' ] },
  { name: 'Christmas Island',
    code2: 'CX',
    code3: 'CXR',
    tld: [ '.cx' ] },
  { name: 'Cocos (Keeling) Islands',
    code2: 'CC',
    code3: 'CCK',
    tld: [ '.cc' ] },
  { name: 'Colombia', code2: 'CO', code3: 'COL', tld: [ '.co' ] },
  { name: 'Comoros', code2: 'KM', code3: 'COM', tld: [ '.km' ] },
  { name: 'Republic of the Congo',
    code2: 'CG',
    code3: 'COG',
    tld: [ '.cg' ] },
  { name: 'Democratic Republic of the Congo',
    code2: 'CD',
    code3: 'COD',
    tld: [ '.cd' ] },
  { name: 'Cook Islands',
    code2: 'CK',
    code3: 'COK',
    tld: [ '.ck' ] },
  { name: 'Costa Rica', code2: 'CR', code3: 'CRI', tld: [ '.cr' ] },
  { name: 'Croatia', code2: 'HR', code3: 'HRV', tld: [ '.hr' ] },
  { name: 'Cuba', code2: 'CU', code3: 'CUB', tld: [ '.cu' ] },
  { name: 'Curaçao', code2: 'CW', code3: 'CUW', tld: [ '.cw' ] },
  { name: 'Cyprus', code2: 'CY', code3: 'CYP', tld: [ '.cy' ] },
  { name: 'Czech Republic',
    code2: 'CZ',
    code3: 'CZE',
    tld: [ '.cz' ] },
  { name: 'Denmark', code2: 'DK', code3: 'DNK', tld: [ '.dk' ] },
  { name: 'Djibouti', code2: 'DJ', code3: 'DJI', tld: [ '.dj' ] },
  { name: 'Dominica', code2: 'DM', code3: 'DMA', tld: [ '.dm' ] },
  { name: 'Dominican Republic',
    code2: 'DO',
    code3: 'DOM',
    tld: [ '.do' ] },
  { name: 'Ecuador', code2: 'EC', code3: 'ECU', tld: [ '.ec' ] },
  { name: 'Egypt', code2: 'EG', code3: 'EGY', tld: [ '.eg' ] },
  { name: 'El Salvador', code2: 'SV', code3: 'SLV', tld: [ '.sv' ] },
  { name: 'Equatorial Guinea',
    code2: 'GQ',
    code3: 'GNQ',
    tld: [ '.gq' ] },
  { name: 'Eritrea', code2: 'ER', code3: 'ERI', tld: [ '.er' ] },
  { name: 'Estonia', code2: 'EE', code3: 'EST', tld: [ '.ee' ] },
  { name: 'Ethiopia', code2: 'ET', code3: 'ETH', tld: [ '.et' ] },
  { name: 'Falkland Islands',
    code2: 'FK',
    code3: 'FLK',
    tld: [ '.fk' ] },
  { name: 'Faroe Islands',
    code2: 'FO',
    code3: 'FRO',
    tld: [ '.fo' ] },
  { name: 'Fiji', code2: 'FJ', code3: 'FJI', tld: [ '.fj' ] },
  { name: 'Finland', code2: 'FI', code3: 'FIN', tld: [ '.fi' ] },
  { name: 'France', code2: 'FR', code3: 'FRA', tld: [ '.fr' ] },
  { name: 'French Guiana',
    code2: 'GF',
    code3: 'GUF',
    tld: [ '.gf' ] },
  { name: 'French Polynesia',
    code2: 'PF',
    code3: 'PYF',
    tld: [ '.pf' ] },
  { name: 'French Southern and Antarctic Lands',
    code2: 'TF',
    code3: 'ATF',
    tld: [ '.tf' ] },
  { name: 'Gabon', code2: 'GA', code3: 'GAB', tld: [ '.ga' ] },
  { name: 'Gambia', code2: 'GM', code3: 'GMB', tld: [ '.gm' ] },
  { name: 'Georgia', code2: 'GE', code3: 'GEO', tld: [ '.ge' ] },
  { name: 'Germany', code2: 'DE', code3: 'DEU', tld: [ '.de' ] },
  { name: 'Ghana', code2: 'GH', code3: 'GHA', tld: [ '.gh' ] },
  { name: 'Gibraltar', code2: 'GI', code3: 'GIB', tld: [ '.gi' ] },
  { name: 'Greece', code2: 'GR', code3: 'GRC', tld: [ '.gr' ] },
  { name: 'Greenland', code2: 'GL', code3: 'GRL', tld: [ '.gl' ] },
  { name: 'Grenada', code2: 'GD', code3: 'GRD', tld: [ '.gd' ] },
  { name: 'Guadeloupe', code2: 'GP', code3: 'GLP', tld: [ '.gp' ] },
  { name: 'Guam', code2: 'GU', code3: 'GUM', tld: [ '.gu' ] },
  { name: 'Guatemala', code2: 'GT', code3: 'GTM', tld: [ '.gt' ] },
  { name: 'Guernsey', code2: 'GG', code3: 'GGY', tld: [ '.gg' ] },
  { name: 'Guinea', code2: 'GN', code3: 'GIN', tld: [ '.gn' ] },
  { name: 'Guinea-Bissau',
    code2: 'GW',
    code3: 'GNB',
    tld: [ '.gw' ] },
  { name: 'Guyana', code2: 'GY', code3: 'GUY', tld: [ '.gy' ] },
  { name: 'Haiti', code2: 'HT', code3: 'HTI', tld: [ '.ht' ] },
  { name: 'Heard Island and McDonald Islands',
    code2: 'HM',
    code3: 'HMD',
    tld: [ '.hm', '.aq' ] },
  { name: 'Vatican City',
    code2: 'VA',
    code3: 'VAT',
    tld: [ '.va' ] },
  { name: 'Honduras', code2: 'HN', code3: 'HND', tld: [ '.hn' ] },
  { name: 'Hong Kong', code2: 'HK', code3: 'HKG', tld: [ '.hk' ] },
  { name: 'Hungary', code2: 'HU', code3: 'HUN', tld: [ '.hu' ] },
  { name: 'Iceland', code2: 'IS', code3: 'ISL', tld: [ '.is' ] },
  { name: 'India', code2: 'IN', code3: 'IND', tld: [ '.in' ] },
  { name: 'Indonesia', code2: 'ID', code3: 'IDN', tld: [ '.id' ] },
  { name: 'Ivory Coast', code2: 'CI', code3: 'CIV', tld: [ '.ci' ] },
  { name: 'Iran', code2: 'IR', code3: 'IRN', tld: [ '.ir' ] },
  { name: 'Iraq', code2: 'IQ', code3: 'IRQ', tld: [ '.iq' ] },
  { name: 'Ireland', code2: 'IE', code3: 'IRL', tld: [ '.ie' ] },
  { name: 'Isle of Man', code2: 'IM', code3: 'IMN', tld: [ '.im' ] },
  { name: 'Israel', code2: 'IL', code3: 'ISR', tld: [ '.il' ] },
  { name: 'Italy', code2: 'IT', code3: 'ITA', tld: [ '.it' ] },
  { name: 'Jamaica', code2: 'JM', code3: 'JAM', tld: [ '.jm' ] },
  { name: 'Japan', code2: 'JP', code3: 'JPN', tld: [ '.jp' ] },
  { name: 'Jersey', code2: 'JE', code3: 'JEY', tld: [ '.je' ] },
  { name: 'Jordan', code2: 'JO', code3: 'JOR', tld: [ '.jo' ] },
  { name: 'Kazakhstan',
    code2: 'KZ',
    code3: 'KAZ',
    tld: [ '.kz', '.қаз' ] },
  { name: 'Kenya', code2: 'KE', code3: 'KEN', tld: [ '.ke' ] },
  { name: 'Kiribati', code2: 'KI', code3: 'KIR', tld: [ '.ki' ] },
  { name: 'Kuwait', code2: 'KW', code3: 'KWT', tld: [ '.kw' ] },
  { name: 'Kyrgyzstan', code2: 'KG', code3: 'KGZ', tld: [ '.kg' ] },
  { name: 'Laos', code2: 'LA', code3: 'LAO', tld: [ '.la' ] },
  { name: 'Latvia', code2: 'LV', code3: 'LVA', tld: [ '.lv' ] },
  { name: 'Lebanon', code2: 'LB', code3: 'LBN', tld: [ '.lb' ] },
  { name: 'Lesotho', code2: 'LS', code3: 'LSO', tld: [ '.ls' ] },
  { name: 'Liberia', code2: 'LR', code3: 'LBR', tld: [ '.lr' ] },
  { name: 'Libya', code2: 'LY', code3: 'LBY', tld: [ '.ly' ] },
  { name: 'Liechtenstein',
    code2: 'LI',
    code3: 'LIE',
    tld: [ '.li' ] },
  { name: 'Lithuania', code2: 'LT', code3: 'LTU', tld: [ '.lt' ] },
  { name: 'Luxembourg', code2: 'LU', code3: 'LUX', tld: [ '.lu' ] },
  { name: 'Macau', code2: 'MO', code3: 'MAC', tld: [ '.mo' ] },
  { name: 'Macedonia', code2: 'MK', code3: 'MKD', tld: [ '.mk' ] },
  { name: 'Madagascar', code2: 'MG', code3: 'MDG', tld: [ '.mg' ] },
  { name: 'Malawi', code2: 'MW', code3: 'MWI', tld: [ '.mw' ] },
  { name: 'Malaysia', code2: 'MY', code3: 'MYS', tld: [ '.my' ] },
  { name: 'Maldives', code2: 'MV', code3: 'MDV', tld: [ '.mv' ] },
  { name: 'Mali', code2: 'ML', code3: 'MLI', tld: [ '.ml' ] },
  { name: 'Malta', code2: 'MT', code3: 'MLT', tld: [ '.mt' ] },
  { name: 'Marshall Islands',
    code2: 'MH',
    code3: 'MHL',
    tld: [ '.mh' ] },
  { name: 'Martinique', code2: 'MQ', code3: 'MTQ', tld: [ '.mq' ] },
  { name: 'Mauritania', code2: 'MR', code3: 'MRT', tld: [ '.mr' ] },
  { name: 'Mauritius', code2: 'MU', code3: 'MUS', tld: [ '.mu' ] },
  { name: 'Mayotte', code2: 'YT', code3: 'MYT', tld: [ '.yt' ] },
  { name: 'Mexico', code2: 'MX', code3: 'MEX', tld: [ '.mx' ] },
  { name: 'Micronesia', code2: 'FM', code3: 'FSM', tld: [ '.fm' ] },
  { name: 'Moldova', code2: 'MD', code3: 'MDA', tld: [ '.md' ] },
  { name: 'Monaco', code2: 'MC', code3: 'MCO', tld: [ '.mc' ] },
  { name: 'Mongolia', code2: 'MN', code3: 'MNG', tld: [ '.mn' ] },
  { name: 'Montenegro', code2: 'ME', code3: 'MNE', tld: [ '.me' ] },
  { name: 'Montserrat', code2: 'MS', code3: 'MSR', tld: [ '.ms' ] },
  { name: 'Morocco', code2: 'MA', code3: 'MAR', tld: [ '.ma' ] },
  { name: 'Mozambique', code2: 'MZ', code3: 'MOZ', tld: [ '.mz' ] },
  { name: 'Myanmar', code2: 'MM', code3: 'MMR', tld: [ '.mm' ] },
  { name: 'Namibia', code2: 'NA', code3: 'NAM', tld: [ '.na' ] },
  { name: 'Nauru', code2: 'NR', code3: 'NRU', tld: [ '.nr' ] },
  { name: 'Nepal', code2: 'NP', code3: 'NPL', tld: [ '.np' ] },
  { name: 'Netherlands', code2: 'NL', code3: 'NLD', tld: [ '.nl' ] },
  { name: 'New Caledonia',
    code2: 'NC',
    code3: 'NCL',
    tld: [ '.nc' ] },
  { name: 'New Zealand', code2: 'NZ', code3: 'NZL', tld: [ '.nz' ] },
  { name: 'Nicaragua', code2: 'NI', code3: 'NIC', tld: [ '.ni' ] },
  { name: 'Niger', code2: 'NE', code3: 'NER', tld: [ '.ne' ] },
  { name: 'Nigeria', code2: 'NG', code3: 'NGA', tld: [ '.ng' ] },
  { name: 'Niue', code2: 'NU', code3: 'NIU', tld: [ '.nu' ] },
  { name: 'Norfolk Island',
    code2: 'NF',
    code3: 'NFK',
    tld: [ '.nf' ] },
  { name: 'North Korea', code2: 'KP', code3: 'PRK', tld: [ '.kp' ] },
  { name: 'Northern Mariana Islands',
    code2: 'MP',
    code3: 'MNP',
    tld: [ '.mp' ] },
  { name: 'Norway', code2: 'NO', code3: 'NOR', tld: [ '.no' ] },
  { name: 'Oman', code2: 'OM', code3: 'OMN', tld: [ '.om' ] },
  { name: 'Pakistan', code2: 'PK', code3: 'PAK', tld: [ '.pk' ] },
  { name: 'Palau', code2: 'PW', code3: 'PLW', tld: [ '.pw' ] },
  { name: 'Palestine', code2: 'PS', code3: 'PSE', tld: [ '.ps' ] },
  { name: 'Panama', code2: 'PA', code3: 'PAN', tld: [ '.pa' ] },
  { name: 'Papua New Guinea',
    code2: 'PG',
    code3: 'PNG',
    tld: [ '.pg' ] },
  { name: 'Paraguay', code2: 'PY', code3: 'PRY', tld: [ '.py' ] },
  { name: 'Peru', code2: 'PE', code3: 'PER', tld: [ '.pe' ] },
  { name: 'Philippines', code2: 'PH', code3: 'PHL', tld: [ '.ph' ] },
  { name: 'Pitcairn Islands',
    code2: 'PN',
    code3: 'PCN',
    tld: [ '.pn' ] },
  { name: 'Poland', code2: 'PL', code3: 'POL', tld: [ '.pl' ] },
  { name: 'Portugal', code2: 'PT', code3: 'PRT', tld: [ '.pt' ] },
  { name: 'Puerto Rico', code2: 'PR', code3: 'PRI', tld: [ '.pr' ] },
  { name: 'Qatar', code2: 'QA', code3: 'QAT', tld: [ '.qa' ] },
  { name: 'Republic of Kosovo',
    code2: 'XK',
    code3: 'KOS',
    tld: [ '' ] },
  { name: 'Réunion', code2: 'RE', code3: 'REU', tld: [ '.re' ] },
  { name: 'Romania', code2: 'RO', code3: 'ROU', tld: [ '.ro' ] },
  { name: 'Russia', code2: 'RU', code3: 'RUS', tld: [ '.ru' ] },
  { name: 'Rwanda', code2: 'RW', code3: 'RWA', tld: [ '.rw' ] },
  { name: 'Saint Barthélemy',
    code2: 'BL',
    code3: 'BLM',
    tld: [ '.bl' ] },
  { name: 'Saint Helena',
    code2: 'SH',
    code3: 'SHN',
    tld: [ '.sh' ] },
  { name: 'Saint Kitts and Nevis',
    code2: 'KN',
    code3: 'KNA',
    tld: [ '.kn' ] },
  { name: 'Saint Lucia', code2: 'LC', code3: 'LCA', tld: [ '.lc' ] },
  { name: 'Saint Martin',
    code2: 'MF',
    code3: 'MAF',
    tld: [ '.mf', '.fr', '.gp' ] },
  { name: 'Saint Pierre and Miquelon',
    code2: 'PM',
    code3: 'SPM',
    tld: [ '.pm' ] },
  { name: 'Saint Vincent and the Grenadines',
    code2: 'VC',
    code3: 'VCT',
    tld: [ '.vc' ] },
  { name: 'Samoa', code2: 'WS', code3: 'WSM', tld: [ '.ws' ] },
  { name: 'San Marino', code2: 'SM', code3: 'SMR', tld: [ '.sm' ] },
  { name: 'São Tomé and Príncipe',
    code2: 'ST',
    code3: 'STP',
    tld: [ '.st' ] },
  { name: 'Saudi Arabia',
    code2: 'SA',
    code3: 'SAU',
    tld: [ '.sa' ] },
  { name: 'Senegal', code2: 'SN', code3: 'SEN', tld: [ '.sn' ] },
  { name: 'Serbia', code2: 'RS', code3: 'SRB', tld: [ '.rs' ] },
  { name: 'Seychelles', code2: 'SC', code3: 'SYC', tld: [ '.sc' ] },
  { name: 'Sierra Leone',
    code2: 'SL',
    code3: 'SLE',
    tld: [ '.sl' ] },
  { name: 'Singapore', code2: 'SG', code3: 'SGP', tld: [ '.sg' ] },
  { name: 'Sint Maarten',
    code2: 'SX',
    code3: 'SXM',
    tld: [ '.sx' ] },
  { name: 'Slovakia', code2: 'SK', code3: 'SVK', tld: [ '.sk' ] },
  { name: 'Slovenia', code2: 'SI', code3: 'SVN', tld: [ '.si' ] },
  { name: 'Solomon Islands',
    code2: 'SB',
    code3: 'SLB',
    tld: [ '.sb' ] },
  { name: 'Somalia', code2: 'SO', code3: 'SOM', tld: [ '.so' ] },
  { name: 'South Africa',
    code2: 'ZA',
    code3: 'ZAF',
    tld: [ '.za' ] },
  { name: 'South Georgia',
    code2: 'GS',
    code3: 'SGS',
    tld: [ '.gs' ] },
  { name: 'South Korea', code2: 'KR', code3: 'KOR', tld: [ '.kr' ] },
  { name: 'South Sudan', code2: 'SS', code3: 'SSD', tld: [ '.ss' ] },
  { name: 'Spain', code2: 'ES', code3: 'ESP', tld: [ '.es' ] },
  { name: 'Sri Lanka', code2: 'LK', code3: 'LKA', tld: [ '.lk' ] },
  { name: 'Sudan', code2: 'SD', code3: 'SDN', tld: [ '.sd' ] },
  { name: 'Suriname', code2: 'SR', code3: 'SUR', tld: [ '.sr' ] },
  { name: 'Svalbard and Jan Mayen',
    code2: 'SJ',
    code3: 'SJM',
    tld: [ '.sj' ] },
  { name: 'Swaziland', code2: 'SZ', code3: 'SWZ', tld: [ '.sz' ] },
  { name: 'Sweden', code2: 'SE', code3: 'SWE', tld: [ '.se' ] },
  { name: 'Switzerland', code2: 'CH', code3: 'CHE', tld: [ '.ch' ] },
  { name: 'Syria', code2: 'SY', code3: 'SYR', tld: [ '.sy' ] },
  { name: 'Taiwan', code2: 'TW', code3: 'TWN', tld: [ '.tw' ] },
  { name: 'Tajikistan', code2: 'TJ', code3: 'TJK', tld: [ '.tj' ] },
  { name: 'Tanzania', code2: 'TZ', code3: 'TZA', tld: [ '.tz' ] },
  { name: 'Thailand', code2: 'TH', code3: 'THA', tld: [ '.th' ] },
  { name: 'Timor-Leste', code2: 'TL', code3: 'TLS', tld: [ '.tl' ] },
  { name: 'Togo', code2: 'TG', code3: 'TGO', tld: [ '.tg' ] },
  { name: 'Tokelau', code2: 'TK', code3: 'TKL', tld: [ '.tk' ] },
  { name: 'Tonga', code2: 'TO', code3: 'TON', tld: [ '.to' ] },
  { name: 'Trinidad and Tobago',
    code2: 'TT',
    code3: 'TTO',
    tld: [ '.tt' ] },
  { name: 'Tunisia', code2: 'TN', code3: 'TUN', tld: [ '.tn' ] },
  { name: 'Turkey', code2: 'TR', code3: 'TUR', tld: [ '.tr' ] },
  { name: 'Turkmenistan',
    code2: 'TM',
    code3: 'TKM',
    tld: [ '.tm' ] },
  { name: 'Turks and Caicos Islands',
    code2: 'TC',
    code3: 'TCA',
    tld: [ '.tc' ] },
  { name: 'Tuvalu', code2: 'TV', code3: 'TUV', tld: [ '.tv' ] },
  { name: 'Uganda', code2: 'UG', code3: 'UGA', tld: [ '.ug' ] },
  { name: 'Ukraine', code2: 'UA', code3: 'UKR', tld: [ '.ua' ] },
  { name: 'United Arab Emirates',
    code2: 'AE',
    code3: 'ARE',
    tld: [ '.ae' ] },
  { name: 'United Kingdom',
    code2: 'GB',
    code3: 'GBR',
    tld: [ '.uk' ] },
  { name: 'United States',
    code2: 'US',
    code3: 'USA',
    tld: [ '.us' ] },
  { name: 'United States Minor Outlying Islands',
    code2: 'UM',
    code3: 'UMI',
    tld: [ '.us' ] },
  { name: 'United States Virgin Islands',
    code2: 'VI',
    code3: 'VIR',
    tld: [ '.vi' ] },
  { name: 'Uruguay', code2: 'UY', code3: 'URY', tld: [ '.uy' ] },
  { name: 'Uzbekistan', code2: 'UZ', code3: 'UZB', tld: [ '.uz' ] },
  { name: 'Vanuatu', code2: 'VU', code3: 'VUT', tld: [ '.vu' ] },
  { name: 'Venezuela', code2: 'VE', code3: 'VEN', tld: [ '.ve' ] },
  { name: 'Vietnam', code2: 'VN', code3: 'VNM', tld: [ '.vn' ] },
  { name: 'Wallis and Futuna',
    code2: 'WF',
    code3: 'WLF',
    tld: [ '.wf' ] },
  { name: 'Western Sahara',
    code2: 'EH',
    code3: 'ESH',
    tld: [ '.eh' ] },
  { name: 'Yemen', code2: 'YE', code3: 'YEM', tld: [ '.ye' ] },
  { name: 'Zambia', code2: 'ZM', code3: 'ZMB', tld: [ '.zm' ] },
  { name: 'Zimbabwe', code2: 'ZW', code3: 'ZWE', tld: [ '.zw' ] } ]

  var europeanCountries = [ 
  	'AL',
  	'AD',
  	'AT',
  	'BY',
  	'BE',
  	'BA',
  	'BG',
  	'HR',
  	'CY',
  	'CZ',
  	'DK',
  	'EE',
  	'FO',
  	'FI',
  	'FR',
  	'DE',
  	'GI',
  	'GR',
  	'HU',
  	'IS',
  	'IE',
  	'IT',
  	'LV',
  	'LI',
  	'LT',
  	'LU',
  	'MK',
  	'MT',
  	'MD',
  	'MC',
  	'NL',
  	'NO',
  	'PL',
  	'PT',
  	'RO',
  	'RU',
  	'SM',
  	'RS',
  	'SK',
  	'SI',
  	'ES',
  	'SE',
  	'CH',
  	'UA',
  	'GB',
  	'VA',
  	'RS',
  	'IM',
  	'RS',
  	'ME' ]

  var EUCountries = [ 
  	'AT',
  	'BE',
  	'BG',
  	'HR',
  	'CY',
  	'CZ',
  	'DK',
  	'EE',
  	'FI',
  	'FR',
  	'DE',
  	'GR',
  	'HU',
  	'IE',
  	'IT',
  	'LV',
  	'LT',
  	'LU',
  	'MT',
  	'NL',
  	'PL',
  	'PT',
  	'RO',
  	'SK',
  	'SI',
  	'ES',
  	'SE',
  	'GB' 
  ]
  
  return country;
});
